name: NotificationSlack

on:
  push:
    tags:
      - 'v*'

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Envoi d'un message Slack
        id: slack
        uses: slackapi/slack-github-action@v1.15.0
        with:
          payload: "{\"text\":\"La librairie *Lib-KoaSwagger* vient d'être mise à jour en ${{ env.RELEASE_VERSION }} !\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}